#使用缓存重用node_modules
cache:
  paths:
    - chapter02/backend-app/node_modules
    - chapter02/backend-app/dist
#安装与编译
build-chapter02/backend-app: 
  stage: build
  script:
    - echo "Compiling the code..."
    - cd chapter02/backend-app/
    - npm install --silent
    - npm run build
#执行单元测试
unit-test-chapter02/backend-app: 
  stage: test 
  script:
    - echo "Running unit tests..."
#development部署
deploy-build-chapter02-development: 
  stage: deploy 
  image:
    # name: gcr.io/kaniko-project/executor:v1.9.0-debug
    name: topabomb/kaniko-executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - echo "Deploying chapter02/backend-app application to development..."
    - /kaniko/executor
      --insecure
      --insecure-registry "172.18.72.18:32000"
      --context "${CI_PROJECT_DIR}/chapter02/backend-app"
      --dockerfile "${CI_PROJECT_DIR}/chapter02/backend-app/Dockerfile"
      --destination "172.18.72.18:32000/:v1.0.0" #--destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
